apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: service2-svc
  annotations:
    cloud.google.com/backend-config: '{"ports": { "service2":"service2-health" }}'
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: service2
  type: ClusterIP
  selector:
    app: service2-deployment
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: service2-health
  namespace: example
spec:
  timeoutSec: 120
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /api/service2/health/check
    port: 8081
