apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: service1-svc
  annotations:
    cloud.google.com/backend-config: '{"ports": { "service1":"service1-health" }}'
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: service1
  type: ClusterIP
  selector:
    app: service1-deployment
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: service1-health
  namespace: example
spec:
  timeoutSec: 120
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /api/service1/health/check
    port: 8080
