---
- name: Setup kubernetes common
  hosts: kcontrol, knodes
  become: true
  become_method: sudo
  become_user: ansible
  gather_facts: true
  roles:
    - kube-common-setup

- name: Setup kubernetes control plane
  hosts: kcontrol
  become: true
  become_method: sudo
  become_user: ansible
  gather_facts: true
  roles:
    - kube-control-setup

- name: Setup kubernetes node
  hosts: knodes
  become: true
  become_method: sudo
  become_user: ansible
  gather_facts: true
  roles:
    - kube-node-setup

- name: Setup kubernetes node
  hosts: kcontrol
  become: true
  become_method: sudo
  become_user: ansible
  gather_facts: true
  roles:
    - post-installation
